### ISSUE TITLE
Umbrella of Things to call it MVP Complete

### ISSUE THREAD

**Issue by hrgui** [hrgui/my-webpack-boilerplate#1]
# Build
- [x] I can do React
- [x] I can do Tailwind
- [x] I can do CSS Modules
- [x] I can load a SVG in development
- [x] Public directory linking of public assets

# Deploy
- [x] It can be deployed to Github Pages that is not the root
